[package]
name = "snake"
version = "0.1.0"
description = "Simple Snake game made in Rust with Ratatui crate"
authors = ["melch"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
